---
title: mad-universe.com
url: http://mad-universe.siteleaf.net
timezone: Pacific Time (US & Canada)
permalink: pretty
chris_email: chris@mad-universe.com
dark_blue: "#000910"
light_yellow: "#fafae5"
dark_grey: "#333333"
light_green: "#e6f9ee"
collections:
  uploads:
    title: Uploads
    output: true
  news:
    output: true
  projects:
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/posts/:title/"
markdown: redcarpet
redcarpet:
  extensions:
  - autolink
  - fenced_code_blocks
  - lax_spacing
  - strikethrough
  - superscript
  - tables
  - footnotes
  - highlight
